# Generated by Django 3.1.7 on 2021-05-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='drugtype',
            field=models.CharField(blank=True, choices=[('Capsules', 'Capsules'), ('Injection', 'Injection'), ('Liquid', 'Liquid'), ('Tablet', 'Tablet')], max_length=255, null=True),
        ),
    ]
